version: '3.9'

services:
  backend:
    image: "${CI_REGISTRY}/${CI_REGISTRY_REPO}/blockscout:${SERVICE_TAG}"
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:4000/api/v2/config >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 60s
    labels:
      com.atleta.role: "blockscout"
      com.atleta.service: "backend"
