version: '3.9'

services:
  frontend:
    image: "${CI_REGISTRY}/${CI_REGISTRY_REPO}/blockscout-frontend:${SERVICE_TAG}"
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    labels:
      com.atleta.role: "blockscout"
      com.atleta.service: "frontend"
