version: '3.9'

services:
  proxy:
    image: nginx
    #pull_policy: never
    container_name: proxy
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/www/:/var/www/certbot/
      - /var/log/nginx/:/var/log/nginx
      - ./.well-known:/var/www/reown/.well-known
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081

